-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `nama` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `telepon` VARCHAR(191) NULL,
    `role` ENUM('WARGA', 'PETUGAS', 'ADMIN') NOT NULL DEFAULT 'WARGA',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pengaduan` (
    `id` VARCHAR(191) NOT NULL,
    `namaLengkap` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `alamat` TEXT NULL,
    `provinsi` VARCHAR(191) NULL,
    `kota` VARCHAR(191) NULL,
    `noTelepon` VARCHAR(191) NULL,
    `fotoKtp` VARCHAR(191) NULL,
    `jenisKasus` ENUM('AKSES_ILEGAL', 'ANCAMAN_KEKERASAN', 'ANCAMAN_PENCEMARAN', 'BERITA_BOHONG', 'CRACKING', 'EKSFILTRASI_DATA', 'FASILITASI_KEJAHATAN_SIBER', 'GANGGUAN_SISTEM', 'INTERSEPSI', 'INTRUSI', 'JUDI_ONLINE', 'MANIPULASI_DATA_DARI_INTERSEPSI', 'MANIPULASI_DATA_YANG_TIDAK_SAH', 'NARKOBA_ILLEGAL', 'PENCEMARAN_NAMA_BAIK', 'PENCURIAN_DATA', 'PENGUNGKAPAN_DATA_YANG_TIDAK_SAH', 'PENIPUAN_ONLINE', 'PERDAGANGAN_HEWAN_YANG_DILINDUNGI', 'PERDAGANGAN_ORANG', 'PERUNDUNGAN_ONLINE', 'PORNOGRAFI', 'PROSTITUSI', 'PROVOKASI_PENGHASUTAN', 'UJARAN_KEBENCIAN', 'LAINNYA') NOT NULL,
    `akunTerlapor` VARCHAR(191) NOT NULL,
    `pesan` TEXT NOT NULL,
    `lampiran` VARCHAR(191) NULL,
    `status` ENUM('PENDING', 'PROSES', 'SELESAI', 'DITOLAK') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `userId` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tanggapan` (
    `id` VARCHAR(191) NOT NULL,
    `isiTanggapan` TEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `pengaduanId` VARCHAR(191) NOT NULL,
    `petugasId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `pengaduan` ADD CONSTRAINT `pengaduan_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tanggapan` ADD CONSTRAINT `tanggapan_pengaduanId_fkey` FOREIGN KEY (`pengaduanId`) REFERENCES `pengaduan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tanggapan` ADD CONSTRAINT `tanggapan_petugasId_fkey` FOREIGN KEY (`petugasId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
